# Generated by Django 4.2.4 on 2023-08-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                ("public_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("user", "User"),
                        ],
                        default="user",
                        max_length=254,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.UUIDField()),
                ("debit", models.IntegerField(default=0)),
                ("credit", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("public_id", models.UUIDField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=254)),
                ("jira_id", models.CharField(max_length=254, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Done"), ("in_progress", "In Progress")],
                        max_length=254,
                    ),
                ),
                ("assignee", models.UUIDField()),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("price", models.IntegerField(default=0)),
                ("fee", models.IntegerField(default=0)),
            ],
        ),
    ]
