# Generated by Django 4.2.4 on 2023-08-15 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authuser",
            name="username",
        ),
    ]
