# Generated by Django 4.2.4 on 2023-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_task_fee_task_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="jira_id",
            field=models.CharField(default="[jira-id]", max_length=254),
            preserve_default=False,
        ),
    ]
