# Generated by Django 4.2.4 on 2023-08-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="jira_id",
            field=models.CharField(max_length=254, null=True),
        ),
    ]
